name: smartrr
description: Smart Reporting & Reffering App.

version: 1.0.8+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.4
  flutter_launcher_icons: ^0.11.0
  splashscreen: ^1.2.0
  google_maps_flutter: any
  location: ^4.3.0
  http: ^0.13.4
  firebase_core: ^2.3.0
  firebase_auth: any
  cloud_firestore: ^4.1.0
  mailer: ^5.1.0
  fluttertoast: ^8.0.9
  google_fonts: ^3.0.1
  shared_preferences: ^2.0.13
  package_info: ^2.0.2
  im_stepper: ^1.0.1+1
  dialog_flowtter: ^0.3.3
  accordion: ^2.2.1
  provider: ^6.0.2
  page_transition: ^2.0.5
  url_launcher: ^6.0.20
  intl: ^0.17.0
  translator: ^0.1.7
  flutter_tts: ^3.3.3
  youtube_player_flutter: ^8.0.0
  flutter_svg: ^1.0.3
  intl_phone_number_input: ^0.7.0+2
  pinput: ^2.2.31
  speech_to_text: ^6.1.0
  uuid: ^3.0.6
  firebase_app_check: ^0.1.1+5
  video_player: ^2.4.8
  chewie: ^1.3.5
  better_player:
    git:
      url: https://github.com/tintran-dev/betterplayer.git
  flutter_animate: ^2.0.1
  flutter_paystack: ^1.0.7
  envied: ^0.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  dart_date: ^1.1.1
  flutter_local_notifications: ^13.0.0
  table_calendar: ^3.0.8
  firebase_messaging: ^14.2.5
  flutter_feather_icons: ^2.0.0+1
  simple_ripple_animation: ^0.0.7
  sentry_flutter: ^7.4.0
  dart_jsonwebtoken: ^2.7.1
  flutter_downloader: ^1.10.2
  permission_handler: ^10.2.0
  workmanager: ^0.5.1

dev_dependencies:
  build_runner: ^2.3.2
  envied_generator: ^0.3.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  # generate: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
flutter_intl:
  enabled: true
